<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lokaliti;

class LokalitSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            'KUALA MUDA MK 1',
            'TMN KUALA MUDA',
            'PMTG TOK LABU',
            'BAKAU TUA MK 1',
            'KG GURUN MK 2',
            'KG TOK OTEK',
            'P. MERTAJAM MK 1',
            'PMTG BENDAHARI',
            'SG KEDAK MK 1',
            'TK MARNAN MK 1',
            'PASIR GEBU MK 2',
            'PERMATANG KERIANG MK 1',
            'TAMAN DESA KUALA MUDA',
            'PASIR GEBU MK 1',
            'PERMATANG RAWA MK 1',
            'KAMPONG DUA PULOH MK 1',
            'KAMPONG SRI PANTAI',
            'SUNGEI TEMBUS MK 4',
            'KAMPUNG BAKAR KAPOR PENAGA',
            'KAMPONG BARU MK 5 PENAGA',
            'PADANG TEMBUSU MK 5',
            'LAHAR ENDIN',
            'TAMAN BERKAT',
            'TMN PENAGA',
            'PENAGA',
            'TMN KUALA BEKAH',
            'TAMAN PENAGA PERMAI',
            'KOTA AUR MK 2',
            'RANTAU PANJANG KEPALA BATAS',
            'PERMATANG TOK IBRAHIM MK 2',
            'PENGKALAN BONGOR KEPALA BATAS',
            'LAHAR MINYAK MK 2',
            'PMTG JANGGUS MK 2',
            'KG LEMBAH',
            'BUMBONG LIMA MK 2',
            'DUSUN LADA MK 2',
            'GUAR KEPAH MK 2',
            'JAMBATAN MERDEKA',
            'GUAR TO SAYID MK 5',
            'KAMPONG PADANG MK 5(2)',
            'LAHAR IKAN MATI MK 5 (BERHADAPAN TAMAN PAYA KELADI)',
            'LAHAR KEPAR MK 5(2)',
            'PERMATANG TIGA RINGGIT MK 5',
            'PERMATANG TINGGI A',
            'KAMPONG PADANG MK 5',
            'LAHAR KEPAR MK 5',
            'PAYA LAHAR MK 5',
            'KUALA BEKAH MK 4',
            'SG ABDUL',
            'PADANG BENGGALI MK 4',
            'TAMAN BINTANG PADANG BENGGALI',
            'LAHAR TABUT MK 4',
            'TITI MUKIM MK 7',
            'PERMATANG BERAH MK 4',
            'PERMATANG KUALA MK 4',
            'PERMATANG PAK MARAS MK 4',
            'PERMATANG PAUH MK 4',
            'KG EMPAT PULOH',
            'PENAGA DUA',
            'PANGSAPURI TITI MUKIM',
            'PMTG KUANG MK 5',
            'PMTG RAMBAI',
            'KG BAHRU MK 5',
            'KG TENGAH MK 5',
            'PMTG SINTOK',
            'PMTG PAK ELONG MK 8',
            'PMTG SINTOK MK 8',
            'KG TOK LOBA',
            'JALAN BUTTERWORTH MK 8',
            'JALAN PERAK KEPALA BATAS',
            'PERMATANG BERTAM MUKIM 8',
            'PERMATANG MANGGIS MK 8',
            'LRG BAHAGIA SATU',
            'TMN BAHAGIA KEPALA BATAS',
            'PENGUNDI TIDAK HADIR',
            'JALAN BUTTERWORTH MK 5',
            'JALAN KEDAH MK 5',
            'KAMPONG DATOK MK 5',
            'KEPALA BATAS MK 5',
            'JLN BESAR KEPALA BATAS MK 5',
            'PERMATANG MANGGIS MK 5',
            'LAHAR IKAN MATI MK 5 (KAW SURAU SIMPANG MEDAN SELARA)',
            'TAMAN SEPAKAT KEPALA BATAS',
            'JLN MALINJA',
            'TAMAN AMAN PUTERA',
            'JLN BERTAM MK 6',
            'JLN LDG BERTAM MK 6',
            'JALAN KEDAH MK 6',
            'JALAN SEKOLAH MK 6',
            'KAMPONG DATOK MK 6',
            'KAMPONG KOVIL MK 6',
            'KAMPONG SETOL MK 6',
            'KEPALA BATAS MK 6',
            'JLN KELINIK MK 6',
            'BRK POLIS KEPALA BATAS',
            'JLN SATU LAHAR BUBU',
            'LRG BERTAM 1',
            'TKT BERTAM 2',
            'KUARTERS HOSPITAL KEPALA BATAS',
            'JLN PADANG KELAB',
            'LAHAR IKAN MATI MK 6',
            'TMN SRI BERTAM',
            'TAMAN BERTAM PERMATA',
            'BEKAS POLIS JALAN KEDAH',
            'BALAI POLIS KEPALA BATAS',
            'IPD SPU',
            'PONGSU SERIBU MK 6',
            'JLN DATUK HJ AHMAD BADAWI',
            'TMN ABDULLAH FAHIM',
            'JLN DUA LAHAR BUBU',
            'JLN TIGA LAHAR BUBU',
            'TMN RUPAWAN',
            'TMN CAHAYA SERIBU',
            'TMN SERI SERDANG',
            'TMN BERTAM SELATAN',
            'TMN BERTAM JAYA',
            'TMN SERI RUPAWAN',
            'TAMAN BERTAM RIA',
            'TAMAN BERTAM FLORA',
            'TAMAN RUPAWAN INDAH KEPALA BATAS',
            'BUMBONG LIMA MUKIM 3',
            'DUSUN LADA MK 3',
            'LUBOK PUSING MK 3',
            'PANTAI KEMLON MK 3',
            'PERMATANG DAMAR MUKIM 3',
            'PERMATANG TINGGI MK 3',
            'TANJONG RAMBAI MUKIM 3',
            'BEREK POLIS BUMBONG LIMA',
            'QRS INS PERTANIAN BUMBONG LIMA',
            'LAHAR IKAN MATI',
            'PAYA KELADI MESJID',
            'PAYA KELADI TENGAH',
            'PAYA KELADI UJONG',
            'PMTG TIGA RINGGIT MK 3',
            'PMTG TINGGI MK 6',
            'TMN BERTAM PERMAI',
            'LRG BENTARA 1',
            'TMN PAYA KELADI',
            'TMN BERTAM PERDANA',
            'PERMATANG TINGGI C',
            'LDG BERTAM MK 6',
            'LDG BERTAM BHG A',
            'LDG BERTAM BHG B',
            'LDG BERTAM BHG C',
            'TMN BERTAM INDAH',
            'PSRN BERTAM 6',
            'PSRN BERTAM 2_3',
            'PSRN BERTAM 7',
            'PSRN BERTAM 8',
            'PSRN BERTAM 2_1',
            'PSRN BERTAM 1',
            'PENANG GOLF RESORT KEPALA BATAS',
            'TAMAN BERTAM SAUJANA',
            'POKOK MACHANG',
            'MALAKOFF ESTATE',
            'AYER MELINTAS',
            'KAMPONG KUBANG MENERONG MK 6',
            'KAMPONG TASEK',
            'KAMPONG TO BEDU MK 6',
            'POKOK JENEREH',
            'AIR MELINTAS BESAR',
            'BANDAR PUTRA BERTAM',
            'KUATERS INST. LATIHAN PERINDUSTRIAN',
            'TAMAN SRI GELUGOR',
            'PANGSAPURI MEKARSARI',
            'TAMAN MEKAR SARI',
            'LAHAR TIANG MK 3',
            'PERMATANG LANGSAT MK 3',
            'PMTG DURIAN MK 3',
            'KG TAMBANG',
            'BERTAM PERDANA 4',
            'EKOR KUCHING MK 3',
            'KAMPONG SETOL MK 3',
            'LEMBAH RAJA MK 3',
            'PADANG BEKA MK 3',
            'PERMATANG SETAR MK 3',
            'PINANG TUNGGAL MK 3',
            'BUKIT SEMENTUL MK 3',
            'PMTG SAGA MK 3',
            'SG KOROK MK 3',
            'KG SIAM (PENAGA PINANG TUNGGAL)',
            'EKOR KUCHING MK 12',
            'KAMPUNG BAHARU MK 12 PINANG TUNGGAL',
            'KG SUNGAI KOROK',
            'TMN DESA EKOR KUCING',
            'TMN SELESA KAMPUNG SELAMAT',
            'JLN PINANG TUNGGAL',
            'KG SELAMAT UTARA',
            'JLN PADANG SERAI',
            'TINGKAT SELAMAT 6',
            'TINGKAT SELAMAT 7',
            'TINGKAT SELAMAT 8',
            'TINGKAT SELAMAT 9',
            'TINGKAT SELAMAT 10',
            'KUBANG MENERONG MK 12',
            'TMN SRI MENERONG',
            'JLN KUBANG MENERONG',
            'TAMAN PERDA INDAH',
            'KG SELAMAT SELATAN',
            'JLN BESAR KG SELAMAT',
            'JALAN PADANG SERAI MK 12',
            'TINGKAT SELAMAT 1',
            'TKT SELAMAT 2',
            'TKT SELAMAT 3',
            'TKT SELAMAT 4',
            'TKT SELAMAT 5',
            'JLN KG BARU',
        ];

        foreach ($names as $nama) {
            Lokaliti::updateOrCreate(['nama' => $nama], ['nama' => $nama]);
        }
    }
}
