---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chilloc1/sistemdatapengundi.com/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess 2>/dev/null || true
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader --no-interaction
    - php artisan key:generate --force
    - php artisan storage:link --force
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - npm install --production
    - npm run build
    - chmod -R 755 storage bootstrap/cache
