---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chilloc1/sistemdatapengundi.com/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - npm install
    - npm run build
